import {  Jura } from "next/font/google";
import "./globals.css";


const jura = Jura({
  variable: "--font-Jura",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jura.variable} ${jura.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
